#:schema node_modules/wrangler/config-schema.json
name = "fundacion-san-mateo"
main = ".open-next/cloudflare-output/worker.js"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/cloudflare-output/assets", binding = "ASSETS" }

[observability]
enabled = true

[vars]
# Add environment variables here
